#!/bin/bash

# Alias for home
alias home="pushd ~ && clear"

# Alias for pushd
alias pd="pushd"

# Alias for popd
alias p="popd && clear"

# Alias for clearing terminal then listing
alias x="clear && ls"

# Alias for clearing terminal
alias c="clear"

alias x="clear && ls"

alias xa="clear && ls -a"

# Alias for reloading .zshrc in current terminal
alias reload="source ~/.zshrc && clear"

# Alias for opening .vimrc file
alias nvimrc="nvim ~/.config/nvim"

# Alias for opening .zshrc files
alias zshrc="nvim ~/.zshrc"
alias ali="nvim ~/.config/zsh/aliases"
alias xprt="nvim ~/.config/zsh/exports"
alias actions="nvim ~/.config/zsh/actions"
alias omz="nvim ~/.config/zsh/ohmyzsh"

# Alias for opening .bashrc file
alias tmuxconf="nvim ~/.tmux.conf"

# export LS_COLORS="di=1;36:ex=32:fi=33"
alias ls="ls --color"

# Alias for Neovim
alias vim="nvim"
